/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
//import GUI.dataMobility;
/**
 *
 * @author divyp
 */
public class mainPage extends javax.swing.JFrame {

    /**
     * Creates new form page_1
     */
    dataMobility m;
    public mainPage() {
        initComponents();
    }
    public mainPage(dataMobility a){
        initComponents();
        m=a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sjf = new javax.swing.JButton();
        Ljf = new javax.swing.JButton();
        Fcfs = new javax.swing.JToggleButton();
        RoundRobin = new javax.swing.JButton();
        Srtf = new javax.swing.JButton();
        PriorityNonP = new javax.swing.JButton();
        Lrtf = new javax.swing.JButton();
        Hrrn = new javax.swing.JButton();
        PriorityP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scheduling Algorithms");
        setPreferredSize(new java.awt.Dimension(803, 488));
        getContentPane().setLayout(null);

        Sjf.setText("SJF");
        Sjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SjfActionPerformed(evt);
            }
        });
        getContentPane().add(Sjf);
        Sjf.setBounds(30, 190, 128, 23);

        Ljf.setText("LJF");
        Ljf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LjfActionPerformed(evt);
            }
        });
        getContentPane().add(Ljf);
        Ljf.setBounds(30, 250, 128, 23);

        Fcfs.setText("FCFS");
        Fcfs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FcfsMouseClicked(evt);
            }
        });
        Fcfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FcfsActionPerformed(evt);
            }
        });
        getContentPane().add(Fcfs);
        Fcfs.setBounds(120, 130, 128, 23);

        RoundRobin.setText("Round Robin");
        RoundRobin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundRobinActionPerformed(evt);
            }
        });
        getContentPane().add(RoundRobin);
        RoundRobin.setBounds(210, 310, 128, 23);

        Srtf.setText("SRTF");
        Srtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrtfActionPerformed(evt);
            }
        });
        getContentPane().add(Srtf);
        Srtf.setBounds(210, 190, 128, 23);

        PriorityNonP.setText("Priority Non-Preamptive");
        PriorityNonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityNonPActionPerformed(evt);
            }
        });
        getContentPane().add(PriorityNonP);
        PriorityNonP.setBounds(20, 370, 160, 23);

        Lrtf.setText("LRTF");
        Lrtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LrtfActionPerformed(evt);
            }
        });
        getContentPane().add(Lrtf);
        Lrtf.setBounds(210, 250, 128, 23);

        Hrrn.setText("HRRN");
        Hrrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrrnActionPerformed(evt);
            }
        });
        getContentPane().add(Hrrn);
        Hrrn.setBounds(30, 310, 130, 23);

        PriorityP.setText("Priority Preamptive");
        PriorityP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityPActionPerformed(evt);
            }
        });
        getContentPane().add(PriorityP);
        PriorityP.setBounds(210, 370, 130, 23);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("  Scheduling Algorithms");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 240, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/mainPageBackground.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SjfActionPerformed
        // TODO add your handling code here:
        Sjf jfrm2= new Sjf(m);
//        jfrm2.setTitle("Shortest Job First");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_SjfActionPerformed

    private void PriorityNonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityNonPActionPerformed
        // TODO add your handling code here:
        PriorityNonP jfrm2= new PriorityNonP(m);
//        jfrm2.setTitle("Priority Scheduling");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_PriorityNonPActionPerformed

    private void RoundRobinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundRobinActionPerformed
        // TODO add your handling code here:
        RoundRobin jfrm2= new RoundRobin(m);
//        jfrm2.setTitle("Round Robin Scheduling");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_RoundRobinActionPerformed

    private void FcfsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FcfsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FcfsMouseClicked

    private void FcfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FcfsActionPerformed
        // TODO add your handling code here:
        Fcfs jfrm2= new Fcfs(m);
//        jfrm2.setTitle("First Come First Serve");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_FcfsActionPerformed

    private void SrtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrtfActionPerformed
        // TODO add your handling code here:
        Srtf jfrm2= new Srtf(m);
//        Srtf jfrm2= new Srtf();
//        jfrm2.setTitle("Shortest Remaining Time First");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_SrtfActionPerformed

    private void LrtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LrtfActionPerformed
        // TODO add your handling code here:
        Lrtf jfrm2= new Lrtf(m);
//        jfrm2.setTitle("Longest Remaining Time First");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LrtfActionPerformed

    private void LjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LjfActionPerformed
        // TODO add your handling code here:
        Ljf jfrm2= new Ljf(m);
//        jfrm2.setTitle("Longest Job First");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LjfActionPerformed

    private void HrrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrrnActionPerformed
        // TODO add your handling code here:
        Hrrn jfrm2= new Hrrn(m);
//        jfrm2.setTitle("Longest Job First");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_HrrnActionPerformed

    private void PriorityPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityPActionPerformed
        // TODO add your handling code here:
        PriorityP jfrm2= new PriorityP(m);
//        jfrm2.setTitle("Longest Job First");
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_PriorityPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Fcfs;
    private javax.swing.JButton Hrrn;
    private javax.swing.JButton Ljf;
    private javax.swing.JButton Lrtf;
    private javax.swing.JButton PriorityNonP;
    private javax.swing.JButton PriorityP;
    private javax.swing.JButton RoundRobin;
    private javax.swing.JButton Sjf;
    private javax.swing.JButton Srtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
